// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int times = Integer.parseInt( args[0]);
		int i =0;
		double[] random = new double[times];
		for(i=0;i<times;i++)
		{
			random[i]=Math.random();
		}
		int less = 0;
	int greater=0;
		for(i=0;i<times;i++)
		{
			if(random[i]<=0.5)
			{
				less++;
			}
			else{
				greater++;
			}
		}
		double ratio =0;
		if(less>=greater)
		{
			ratio= (double)greater/(double)less;

		}
		else{
			ratio= (double)less/(double)greater;

		}
		if(less!=0&&greater!=0)
		{
			System.out.println("> 0.5: " + greater+" times");
			System.out.println("<= 0.5: " + less+" times");
			System.out.println("Ratio: " + ratio );


		}		
		else{
			System.out.println("> 0.5: " + greater+" times");
			System.out.println("<= 0.5: " + less+" times");		}
	}
}
